// Auto-generated by @civui/tokens — do not edit

package gov.civui.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * CivUI design tokens for Jetpack Compose.
 * Government design system — WCAG AA accessible, Section 508 compliant.
 */
object CivTokens {

    // region Colors

    object Colors {
        object Primary {
            val lightest = Color(0xFFD9E8F6)
            val lighter = Color(0xFF73B3E7)
            val light = Color(0xFF2378C3)
            val default_ = Color(0xFF005EA2)
            val vivid = Color(0xFF0050D8)
            val dark = Color(0xFF1A4480)
            val darker = Color(0xFF162E51)
        }
        object Error {
            val lighter = Color(0xFFF4E3DB)
            val light = Color(0xFFD63E04)
            val default_ = Color(0xFFB50909)
            val dark = Color(0xFF8B0A03)
        }
        object Warning {
            val lighter = Color(0xFFFAF3D1)
            val light = Color(0xFFFEE685)
            val default_ = Color(0xFFE5A000)
            val dark = Color(0xFF936F38)
        }
        object Success {
            val lighter = Color(0xFFECF3EC)
            val light = Color(0xFF70E17B)
            val default_ = Color(0xFF00A91C)
            val dark = Color(0xFF4D8055)
        }
        object Info {
            val lighter = Color(0xFFE7F6F8)
            val light = Color(0xFF99DEEA)
            val default_ = Color(0xFF00BDE3)
            val dark = Color(0xFF2E6276)
        }
        object Base {
            val lightest = Color(0xFFF0F0F0)
            val lighter = Color(0xFFDFE1E2)
            val light = Color(0xFFA9AEB1)
            val default_ = Color(0xFF71767A)
            val dark = Color(0xFF565C65)
            val darker = Color(0xFF3D4551)
            val darkest = Color(0xFF1B1B1B)
        }
        object White {
            val default_ = Color(0xFFFFFFFF)
        }
        object Black {
            val default_ = Color(0xFF000000)
        }
        object Accent {
            object Cool {
                val lightest = Color(0xFFE1F3F8)
                val light = Color(0xFF97D4EA)
                val default_ = Color(0xFF00BDE3)
                val dark = Color(0xFF28A0CB)
            }
            object Warm {
                val lightest = Color(0xFFF2E4D4)
                val light = Color(0xFFFFBC78)
                val default_ = Color(0xFFFA9441)
                val dark = Color(0xFFC05600)
            }
        }
    }

    // region Dark Colors

    object DarkColors {
        object Primary {
            val lightest = Color(0xFF1A3A5C)
            val lighter = Color(0xFF2E6CA8)
            val light = Color(0xFF5AA3E8)
            val default_ = Color(0xFF73B3E7)
            val vivid = Color(0xFF5EA7F5)
            val dark = Color(0xFFA4CEF4)
            val darker = Color(0xFFD0E4F8)
        }
        object Error {
            val lighter = Color(0xFF4A2020)
            val light = Color(0xFFE87461)
            val default_ = Color(0xFFF28B82)
            val dark = Color(0xFFF5B7B1)
        }
        object Warning {
            val lighter = Color(0xFF4A3D1A)
            val light = Color(0xFFF5D576)
            val default_ = Color(0xFFF5C542)
            val dark = Color(0xFFC9A24D)
        }
        object Success {
            val lighter = Color(0xFF1E3A20)
            val light = Color(0xFF81D88A)
            val default_ = Color(0xFF5CB85C)
            val dark = Color(0xFF7EC97E)
        }
        object Info {
            val lighter = Color(0xFF1A3A40)
            val light = Color(0xFF7DD3E0)
            val default_ = Color(0xFF4DD0E1)
            val dark = Color(0xFF80DEEA)
        }
        object Base {
            val lightest = Color(0xFF2D2D2D)
            val lighter = Color(0xFF3D3D3D)
            val light = Color(0xFF8A8A8A)
            val default_ = Color(0xFFA0A0A0)
            val dark = Color(0xFFC4C4C4)
            val darker = Color(0xFFE0E0E0)
            val darkest = Color(0xFFF0F0F0)
        }
        object White {
            val default_ = Color(0xFF1B1B1B)
        }
        object Black {
            val default_ = Color(0xFFFFFFFF)
        }
        object Accent {
            object Cool {
                val lightest = Color(0xFF1A3A40)
                val light = Color(0xFF6BC5D8)
                val default_ = Color(0xFF4DD0E1)
                val dark = Color(0xFF80DEEA)
            }
            object Warm {
                val lightest = Color(0xFF3D2D1A)
                val light = Color(0xFFF5B87A)
                val default_ = Color(0xFFF5A654)
                val dark = Color(0xFFE8924A)
            }
        }
    }

    // region Spacing

    object Spacing {
        val _0 = 0.dp
        val _1 = 4.dp
        val _2 = 8.dp
        val _3 = 12.dp
        val _4 = 16.dp
        val _5 = 20.dp
        val _6 = 24.dp
        val _8 = 32.dp
        val _10 = 40.dp
        val _12 = 48.dp
        val _16 = 64.dp
        val _20 = 80.dp
        val px = 1.dp
        val _0_5 = 2.dp
        val _1_5 = 6.dp
        val _2_5 = 10.dp
    }

    // region Typography

    object Typography {
        object FontFamily {
            const val sans = "sans-serif"
            const val mono = "Roboto Mono"
        }

        object FontSize {
            val xs = 12.sp
            val sm = 14.sp
            val base = 16.sp
            val lg = 18.sp
            val xl = 20.sp
            val _2xl = 24.sp
            val _3xl = 28.sp
            val _4xl = 36.sp
            val _5xl = 48.sp
        }

        object FontWeights {
            val light = FontWeight.Light
            val regular = FontWeight.Normal
            val semibold = FontWeight.SemiBold
            val bold = FontWeight.Bold
        }

        object LineHeight {
            const val none = 1f
            const val tight = 1.25f
            const val snug = 1.375f
            const val normal = 1.5f
            const val relaxed = 1.625f
            const val loose = 2f
        }
    }

    // region Border

    object Border {
        object Radius {
            val none = 0.dp
            val sm = 2.dp
            val default_ = 4.dp
            val md = 6.dp
            val lg = 8.dp
            val full = 9999.dp
        }

        object Width {
            val _0 = 0.dp
            val _2 = 2.dp
            val _4 = 4.dp
            val default_ = 1.dp
        }
    }

    // region Shadow

    data class ShadowValue(val x: Float, val y: Float, val blur: Float, val color: Color)

    object Shadow {
        val none = ShadowValue(x = 0f, y = 0f, blur = 0f, color = Color.Transparent)
        val sm = ShadowValue(x = 0f, y = 1f, blur = 2f, color = Color.Black.copy(alpha = 0.1f))
        val default_ = ShadowValue(x = 0f, y = 1f, blur = 3f, color = Color.Black.copy(alpha = 0.1f))
        val md = ShadowValue(x = 0f, y = 4f, blur = 6f, color = Color.Black.copy(alpha = 0.1f))
        val lg = ShadowValue(x = 0f, y = 10f, blur = 15f, color = Color.Black.copy(alpha = 0.1f))
    }

    // region Motion

    object Motion {
        object Duration {
            const val instant = 0
            const val fast = 100
            const val normal = 200
            const val slow = 300
            const val slower = 500
        }

        object Easing {
            val linear = androidx.compose.animation.core.CubicBezierEasing(0f, 0f, 1f, 1f)
            val easeIn = androidx.compose.animation.core.CubicBezierEasing(0.4f, 0f, 1f, 1f)
            val easeOut = androidx.compose.animation.core.CubicBezierEasing(0f, 0f, 0.2f, 1f)
            val easeInOut = androidx.compose.animation.core.CubicBezierEasing(0.4f, 0f, 0.2f, 1f)
        }
    }

    // region Focus

    object Focus {
        val outlineColor = Color(0xFF005EA2)
        val outlineWidth = 3.dp
        val outlineOffset = 2.dp
        val shadowColor = Color(0xFFFFFFFF)
        val shadowSpread = 3.dp
    }

    // region Density Scales

    object Scale {
        object Spacious {
            object FontSize {
                val xs = 11.1.sp
                val sm = 13.5.sp
                val base = 18.sp
                val lg = 24.sp
                val xl = 32.sp
                val _2xl = 42.6.sp
                val _3xl = 56.8.sp
                val _4xl = 75.8.sp
                val _5xl = 101.sp
            }
            object Spacing {
                val _1 = 5.dp
                val _2 = 10.dp
                val _3 = 15.dp
                val _4 = 20.dp
                val _5 = 25.dp
                val _6 = 30.dp
                val _8 = 40.dp
                val _10 = 50.dp
                val _12 = 60.dp
                val _16 = 80.dp
                val _20 = 100.dp
                val _0_5 = 3.dp
                val _1_5 = 8.dp
                val _2_5 = 13.dp
            }
            const val bodyLineHeight = 1.6f
            const val headingLineHeight = 1.3f
        }
        object Dense {
            object FontSize {
                val xs = 11.1.sp
                val sm = 12.4.sp
                val base = 14.sp
                val lg = 15.8.sp
                val xl = 17.7.sp
                val _2xl = 19.9.sp
                val _3xl = 22.4.sp
                val _4xl = 25.2.sp
                val _5xl = 28.4.sp
            }
            object Spacing {
                val _1 = 3.dp
                val _2 = 6.dp
                val _3 = 9.dp
                val _4 = 12.dp
                val _5 = 15.dp
                val _6 = 18.dp
                val _8 = 24.dp
                val _10 = 30.dp
                val _12 = 36.dp
                val _16 = 48.dp
                val _20 = 60.dp
                val _0_5 = 2.dp
                val _1_5 = 5.dp
                val _2_5 = 8.dp
            }
            const val bodyLineHeight = 1.4f
            const val headingLineHeight = 1.15f
        }
    }
}
