// Auto-generated by @civui/codegen — do not edit
// Source: packages/schema/src/components/civ-fieldset.schema.ts

import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { CivBaseElement, renderLegend, renderHint, renderError } from '@civui/core';

/**
 * CivUI Fieldset
 *
 * Native fieldset wrapper with legend, hint, and error support.
 * Uses native <fieldset> for automatic disabled cascade to child form elements.
 *
 * In Light DOM, <slot> does not project children. This component
 * moves child elements into the rendered <fieldset> in updated()
 * so that native disabled cascade works correctly.
 *
 * @element civ-fieldset
 */
@customElement('civ-fieldset')
export class CivFieldset extends CivBaseElement {
  @property({ type: String }) legend = '';
  @property({ type: String }) hint = '';
  @property({ type: String }) error = '';
  @property({ type: Boolean, reflect: true }) required = false;
  @property({ type: Boolean, reflect: true }) disabled = false;

  private _hintId = this.generateId('hint');
  private _errorId = this.generateId('error');
  private _childrenMoved = false;

  override connectedCallback(): void {
    super.connectedCallback();
    this._childrenMoved = false;
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (!this._childrenMoved) {
      this._moveChildrenIntoFieldset();
    }
  }

  private _moveChildrenIntoFieldset(): void {
    const fieldset = this.querySelector('fieldset');
    if (!fieldset) return;

    const contentContainer = fieldset.querySelector('[data-civ-fieldset-content]');
    if (!contentContainer) return;

    const children = Array.from(this.childNodes).filter(
      (node) => node !== fieldset && !(node instanceof Comment),
    );
    for (const child of children) {
      contentContainer.appendChild(child);
    }
    this._childrenMoved = true;
  }

  override render() {
    const describedBy = [
      this.hint ? this._hintId : '',
      this.error ? this._errorId : '',
    ]
      .filter(Boolean)
      .join(' ');

    return html`
      <fieldset
        class="civ-fieldset"
        aria-describedby="${describedBy || nothing}"
        ?disabled="${this.disabled}"
      >
        ${renderLegend({ legend: this.legend, required: this.required, textSizeClass: 'civ-text-lg' })}
        ${renderHint(this._hintId, this.hint, true)}
        ${renderError(this._errorId, this.error, true)}
        <div data-civ-fieldset-content></div>
      </fieldset>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'civ-fieldset': CivFieldset;
  }
}
