import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/architecture',
        'getting-started/design-principles',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: { type: 'generated-index', title: 'Components', description: 'All CivUI components organized by category.' },
      items: [
        { type: 'autogenerated', dirName: 'components' },
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      link: { type: 'generated-index', title: 'Patterns', description: 'Guides for composing CivUI components into government form workflows.' },
      items: [
        { type: 'autogenerated', dirName: 'form-patterns' },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      link: { type: 'generated-index', title: 'Foundations', description: 'Design system foundations — tokens, accessibility, patterns, and platform support.' },
      items: [
        { type: 'autogenerated', dirName: 'foundations' },
      ],
    },
    {
      type: 'category',
      label: 'Contract Reference',
      link: { type: 'generated-index', slug: '/contract', title: 'Contract Reference', description: 'Auto-generated per-component contract documentation. Each page captures the platform-neutral schema (props, events, accessibility, form behavior) that every CivUI platform implementation must satisfy. Generated from `@civui/schema` — do not hand-edit. Use the existing per-component pages under "Components" for worked examples and Storybook embeds.' },
      items: [
        { type: 'autogenerated', dirName: 'contract' },
      ],
    },
    {
      type: 'category',
      label: 'MCP Server',
      items: [
        'mcp-server/overview',
        'mcp-server/tools',
        'mcp-server/workflows',
        'mcp-server/form-architecture',
        'mcp-server/va-forms',
        'mcp-server/schema-reference',
      ],
    },
  ],
};

export default sidebars;
