import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/architecture',
        'getting-started/design-principles',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: { type: 'generated-index', title: 'Components', description: 'All CivUI components organized by category.' },
      items: [
        { type: 'autogenerated', dirName: 'components' },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      link: { type: 'generated-index', title: 'Foundations', description: 'Design system foundations — tokens, accessibility, patterns, and platform support.' },
      items: [
        { type: 'autogenerated', dirName: 'foundations' },
      ],
    },
    {
      type: 'category',
      label: 'MCP Server',
      items: [
        'mcp-server/overview',
        'mcp-server/tools',
        'mcp-server/workflows',
        'mcp-server/form-architecture',
        'mcp-server/va-forms',
        'mcp-server/schema-reference',
      ],
    },
  ],
};

export default sidebars;
