// Auto-generated by @civui/codegen — do not edit
// Source: packages/schema/src/components/civ-checkbox.schema.ts

import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { CivFormElement, dispatch, interpolate, renderHint, renderError } from '@civui/core';

/**
 * CivUI Checkbox
 *
 * Accessible checkbox with inline label, optional description, and tile variant.
 * Uses ElementInternals for native form participation.
 *
 * @element civ-checkbox
 */
@customElement('civ-checkbox')
export class CivCheckbox extends CivFormElement {
  @property({ type: Boolean, reflect: true }) checked = false;
  @property({ type: Boolean, reflect: true }) indeterminate = false;
  @property({ type: String }) description = '';
  @property({ type: Boolean, reflect: true }) tile = false;

  private _defaultChecked = false;
  private _descriptionId = this.generateId('desc');

  protected override get _ariaDescribedBy(): string {
    const ids: string[] = [];
    if (this.description) ids.push(this._descriptionId);
    if (this.hint) ids.push(this._hintId);
    if (this.error) ids.push(this._errorId);
    return ids.join(' ') || '';
  }

  override connectedCallback(): void {
    super.connectedCallback();
    if (!this.value) this.value = 'on';
    this._defaultChecked = this.checked;
  }

  override render() {
    const content = html`
      <label class="civ-flex civ-items-start ${this.tile ? 'civ-cursor-pointer' : ''}" for="${this._inputId}">
        <input
          class="civ-check-input focus-visible:civ-focus-ring"
          id="${this._inputId}"
          type="checkbox"
          name="${this.name}"
          .value="${this.value}"
          .checked="${this.checked}"
          ?disabled="${this.disabled}"
          ?required="${this.required}"
          aria-required="${this.required || nothing}"
          aria-checked="${this.indeterminate ? 'mixed' : nothing}"
          aria-invalid="${this.error ? 'true' : nothing}"
          aria-describedby="${this._ariaDescribedBy || nothing}"
          @change="${this._onCheckboxChange}"
        />
        <div>
          <span class="civ-check-label">
            ${this.label}
            ${this.required
              ? html`<abbr class="civ-required-mark" title="required">*</abbr>`
              : nothing}
          </span>
          ${this.description
            ? html`<span id="${this._descriptionId}" class="civ-check-description">${this.description}</span>`
            : nothing}
        </div>
      </label>
    `;

    return html`
      <div class="civ-mb-2 ${this.tile ? 'civ-check-tile' : ''}" data-civ-tile="${this.tile ? '' : nothing}">
        ${content}
        ${renderHint(this._hintId, this.hint)}
        ${renderError(this._errorId, this.error)}
      </div>
    `;
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (changed.has('indeterminate')) {
      const input = this.querySelector('input') as HTMLInputElement | null;
      if (input) input.indeterminate = this.indeterminate;
    }
    if (changed.has('checked')) {
      this._syncFormValue();
    }
  }

  protected override _syncFormValue(): void {
    this.updateFormValue(this.checked ? this.value : null);
  }

  protected override _updateValidity(): void {
    if (typeof this._internals?.setValidity !== 'function') return;
    const anchor = this.querySelector('input') as HTMLElement | null;
    if (this.required && !this.checked) {
      this._internals.setValidity(
        { valueMissing: true },
        this.error || interpolate(this.requiredMessage, { label: this.label || 'This field' }),
        anchor ?? undefined,
      );
    } else {
      this._internals.setValidity({});
    }
  }

  private _onCheckboxChange(e: Event): void {
    const target = e.target as HTMLInputElement;
    this.checked = target.checked;
    this.indeterminate = false;
    dispatch(this, 'civ-input', { checked: this.checked, value: this.value });
    dispatch(this, 'civ-change', { checked: this.checked, value: this.value });
    this.sendAnalytics('change', { checked: this.checked });
  }

  override formResetCallback(): void {
    this.checked = this._defaultChecked;
    this.indeterminate = false;
    this.error = '';
    this.updateFormValue(this._defaultChecked ? this.value : null);
    dispatch(this, 'civ-reset');
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'civ-checkbox': CivCheckbox;
  }
}
