// Docs site Tailwind config.
//
// Theme (colors, spacing, typography, etc.) is inherited from the
// root `tailwind.config.ts` — the same theme that drives Storybook
// and the component packages — so a token-shape change in the root
// flows to both surfaces from one edit. Before 2026-05-28 the two
// configs were hand-copied (~95% duplication); diff drift had
// already crept in (root had borderColor.DEFAULT; app did not), and
// every palette pass forced touching three files (color.tokens.json
// + root config + app config) instead of one.
//
// Two app-only overrides remain:
//   1. content — the docs site scans its own forms/ HTML, its
//      local src/, and the workspace packages/*/src/ Lit sources.
//   2. plugins — registers the .civ-focus-ring / -inverse utilities
//      (no Tailwind built-in) plus a handful of logical shortcuts
//      (.civ-border-s-4, .civ-rounded-s, .civ-me-2, etc.) that
//      Tailwind 3.3+ already emits natively but the docs site
//      historically wired through this plugin. They cost nothing to
//      keep and a future cleanup pass can decide whether they are
//      still earning their place.
//
// The generated packages/tokens/dist/tailwind/preset.js is NOT
// imported here — it diverges from the hand-config in shape (spacing
// key '0_5' vs '0.5', fontWeight.regular vs the 'normal' alias 11
// consumers rely on, missing surface.* and borderColor.DEFAULT) and
// adopting it would silently break utilities like civ-p-0.5 and
// civ-font-normal. Importing the root config preserves those shapes
// exactly.
import type { Config } from 'tailwindcss';
import plugin from 'tailwindcss/plugin';
import baseConfig from '../../tailwind.config';

const config: Config = {
  ...baseConfig,

  // No safelist needed: every `civ-X--variant` class in CivUI is
  // declared as a plain CSS rule in `packages/core/src/styles/
  // components.css`, not generated by Tailwind. Tailwind's safelist
  // only protects JIT-generated *utilities* from purging — it has no
  // effect on plain CSS rules, which are never purged. Verified by
  // `lint:safelist-stale`.
  content: [
    './forms/**/*.html',
    './src/**/*.ts',
    '../../packages/*/src/**/*.ts',
  ],

  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.civ-focus-ring': {
          outline:
            'var(--civ-focus-outline-width) solid var(--civ-focus-outline-color)',
          'outline-offset': 'var(--civ-focus-outline-offset)',
          'box-shadow':
            '0 0 0 calc(var(--civ-focus-outline-offset) + var(--civ-focus-outline-width) + var(--civ-focus-shadow-spread)) var(--civ-focus-shadow-color)',
        },
        '.civ-focus-ring-inverse': {
          outline:
            'var(--civ-focus-outline-width) solid var(--civ-focus-shadow-color)',
          'outline-offset': 'var(--civ-focus-outline-offset)',
          'box-shadow':
            '0 0 0 calc(var(--civ-focus-outline-offset) + var(--civ-focus-outline-width) + var(--civ-focus-shadow-spread)) var(--civ-focus-outline-color)',
        },

        // Logical border-width (replaces border-l-4 / border-l-0)
        '.civ-border-s-4': { 'border-inline-start-width': '4px' },
        '.civ-border-s-0': { 'border-inline-start-width': '0' },

        // Logical rounding (replaces rounded-l / rounded-r)
        '.civ-rounded-s': {
          'border-start-start-radius': 'var(--civ-border-radius-DEFAULT, 0.25rem)',
          'border-end-start-radius': 'var(--civ-border-radius-DEFAULT, 0.25rem)',
        },
        '.civ-rounded-e': {
          'border-start-end-radius': 'var(--civ-border-radius-DEFAULT, 0.25rem)',
          'border-end-end-radius': 'var(--civ-border-radius-DEFAULT, 0.25rem)',
        },

        // Logical margin (replaces mr-2 / ml-2)
        '.civ-me-2': { 'margin-inline-end': 'var(--civ-spacing-2)' },
        '.civ-ms-2': { 'margin-inline-start': 'var(--civ-spacing-2)' },
      });
    }),
  ],
};

export default config;
