import { describe, it, expect } from 'vitest';
import { generateCompose } from './compose.js';
import type { ComponentSchema } from '@civui/schema/types';

function makeSchema(overrides: Partial<ComponentSchema> & { name: string }): ComponentSchema {
  return {
    $schema: '1.0',
    description: 'Test component',
    category: 'form-control',
    extends: 'CivFormElement',
    isGroup: false,
    props: {},
    events: {},
    a11y: { role: 'textbox', requiredIndicator: 'asterisk', errorAnnouncement: 'assertive' },
    renderOrder: [],
    form: { valueMode: 'string', formAssociated: true, resetBehavior: 'restore-default-value' },
    ...overrides,
  };
}

describe('Compose generator', () => {
  describe('text input pattern', () => {
    const schema = makeSchema({
      name: 'civ-text-input',
      props: {
        type: { type: 'enum', description: 'Type', default: 'text', values: ['text', 'email', 'password'] },
        placeholder: { type: 'string', description: 'Placeholder', default: '' },
      },
      widths: {
        default: { webClass: 'civ-w-full', iosPoints: null, androidDp: null },
      },
      platform: {
        android: {
          keyboardType: { text: 'KeyboardType.Text', email: 'KeyboardType.Email', password: 'KeyboardType.Password' },
          capitalization: { email: 'KeyboardCapitalization.None', _default: 'KeyboardCapitalization.Sentences' },
        },
      },
    });
    const output = generateCompose(schema);

    it('generates auto-generated header', () => {
      expect(output).toContain('// Auto-generated by @civui/codegen');
    });

    it('generates @Composable function', () => {
      expect(output).toContain('@Composable');
      expect(output).toContain('fun CivTextInput(');
    });

    it('includes package declaration', () => {
      expect(output).toContain('package gov.civui.components');
    });

    it('generates CivInputType enum', () => {
      expect(output).toContain('enum class CivInputType');
      expect(output).toContain('Text,');
      expect(output).toContain('Email,');
    });

    it('generates keyboard type mapping', () => {
      expect(output).toContain('fun CivInputType.toKeyboardType()');
      expect(output).toContain('KeyboardType.Email');
    });

    it('generates capitalization mapping', () => {
      expect(output).toContain('fun CivInputType.toCapitalization()');
      expect(output).toContain('KeyboardCapitalization.None');
    });

    it('includes TextField composable', () => {
      expect(output).toContain('TextField(');
      expect(output).toContain('onValueChange = { newValue ->');
    });

    it('includes dark mode colors', () => {
      expect(output).toContain('isSystemInDarkTheme()');
      expect(output).toContain('CivTokens.DarkColors');
    });

    it('includes animated border color', () => {
      expect(output).toContain('animateColorAsState(');
    });

    it('includes accessibility semantics', () => {
      expect(output).toContain('contentDescription');
      expect(output).toContain('LiveRegionMode.Assertive');
    });

    it('generates preview function', () => {
      expect(output).toContain('@Preview');
      expect(output).toContain('fun CivTextInputPreview()');
    });

    it('imports material3 TextField', () => {
      expect(output).toContain('import androidx.compose.material3.TextField');
    });
  });

  describe('checkbox pattern', () => {
    const schema = makeSchema({
      name: 'civ-checkbox',
      props: {
        checked: { type: 'boolean', description: 'Checked', default: false },
        description: { type: 'string', description: 'Description', default: '' },
      },
      form: { valueMode: 'boolean', formAssociated: true, resetBehavior: 'restore-default-checked' },
    });
    const output = generateCompose(schema);

    it('uses Checkbox composable', () => {
      expect(output).toContain('Checkbox(');
    });

    it('has checked and onCheckedChange params', () => {
      expect(output).toContain('checked: Boolean,');
      expect(output).toContain('onCheckedChange: (Boolean) -> Unit,');
    });

    it('imports material3 Checkbox', () => {
      expect(output).toContain('import androidx.compose.material3.Checkbox');
    });

    it('has clickable Row for label area', () => {
      expect(output).toContain('.clickable(enabled = !isDisabled)');
    });
  });

  describe('toggle pattern', () => {
    const schema = makeSchema({
      name: 'civ-toggle',
      props: {
        checked: { type: 'boolean', description: 'On state', default: false },
        description: { type: 'string', description: 'Description', default: '' },
      },
      form: { valueMode: 'boolean', formAssociated: true, resetBehavior: 'restore-default-checked' },
    });
    const output = generateCompose(schema);

    it('uses Switch composable', () => {
      expect(output).toContain('Switch(');
    });

    it('imports material3 Switch', () => {
      expect(output).toContain('import androidx.compose.material3.Switch');
    });
  });

  describe('select pattern', () => {
    const schema = makeSchema({
      name: 'civ-select',
      props: {
        options: {
          type: 'array', description: 'Options', default: [],
          items: { value: { type: 'string', description: 'V', required: true }, label: { type: 'string', description: 'L', required: true } },
        },
        emptyLabel: { type: 'string', description: 'Empty label', default: '- Select -' },
      },
    });
    const output = generateCompose(schema);

    it('generates CivOption data class', () => {
      expect(output).toContain('data class CivOption(');
    });

    it('uses ExposedDropdownMenuBox', () => {
      expect(output).toContain('ExposedDropdownMenuBox(');
    });

    it('renders DropdownMenuItem for each option', () => {
      expect(output).toContain('DropdownMenuItem(');
      expect(output).toContain('options.forEach');
    });
  });

  describe('radio group pattern', () => {
    const schema = makeSchema({
      name: 'civ-radio-group',
      isGroup: true,
      category: 'form-group',
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
        orientation: { type: 'enum', description: 'Orientation', default: 'vertical', values: ['vertical', 'horizontal'] },
      },
    });
    const output = generateCompose(schema);

    it('uses legend parameter', () => {
      expect(output).toContain('legend: String,');
    });

    it('generates CivOrientation enum', () => {
      expect(output).toContain('enum class CivOrientation');
      expect(output).toContain('Vertical,');
      expect(output).toContain('Horizontal,');
    });

    it('has content slot parameter', () => {
      expect(output).toContain('content: @Composable () -> Unit');
    });

    it('switches layout based on orientation', () => {
      expect(output).toContain('CivOrientation.Horizontal');
      expect(output).toContain('Row(');
    });
  });

  describe('segmented control pattern', () => {
    const schema = makeSchema({
      name: 'civ-segmented-control',
      isGroup: true,
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
      },
    });
    const output = generateCompose(schema);

    it('uses SingleChoiceSegmentedButtonRow', () => {
      expect(output).toContain('SingleChoiceSegmentedButtonRow(');
    });
  });

  describe('form container pattern', () => {
    const schema = makeSchema({
      name: 'civ-form',
      extends: 'CivBaseElement',
      props: {
        formLabel: { type: 'string', description: 'Label', default: '' },
      },
      form: { valueMode: 'string', formAssociated: false, resetBehavior: 'restore-default-value' },
    });
    const output = generateCompose(schema);

    it('generates simple Column container', () => {
      expect(output).toContain('Column(');
      expect(output).toContain('content()');
    });
  });

  describe('textarea pattern', () => {
    const schema = makeSchema({
      name: 'civ-textarea',
      props: {
        rows: { type: 'number', description: 'Rows', default: 5 },
        maxlength: { type: 'number', description: 'Max length' },
        placeholder: { type: 'string', description: 'Placeholder', default: '' },
      },
    });
    const output = generateCompose(schema);

    it('uses multiline TextField', () => {
      expect(output).toContain('singleLine = false');
    });

    it('generates character count display', () => {
      expect(output).toContain('characters remaining');
    });
  });

  describe('memorable date pattern', () => {
    const schema = makeSchema({
      name: 'civ-memorable-date',
      isGroup: true,
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
        monthLabel: { type: 'string', description: 'Month label', default: 'Month' },
        dayLabel: { type: 'string', description: 'Day label', default: 'Day' },
        yearLabel: { type: 'string', description: 'Year label', default: 'Year' },
      },
    });
    const output = generateCompose(schema);

    it('has month/day/year parameters', () => {
      expect(output).toContain('month: String,');
      expect(output).toContain('day: String,');
      expect(output).toContain('year: String,');
    });

    it('has change callbacks for each field', () => {
      expect(output).toContain('onMonthChange: (String) -> Unit,');
      expect(output).toContain('onDayChange: (String) -> Unit,');
      expect(output).toContain('onYearChange: (String) -> Unit,');
    });
  });
});
