/**
 * Complex Pattern Generators for Lit Web Components
 *
 * Dedicated generators for components that need behavioral code beyond
 * the simple property-to-template mapping handled by the base generator:
 * - textarea: character count display + debounced SR announcements
 * - radio-group: child sync, roving tabindex, keyboard navigation
 * - checkbox-group: child sync, multi-value FormData assembly
 * - segmented-control: child sync, position data, keyboard navigation
 * - date-picker: calendar dialog, keyboard grid nav, date math
 * - file-upload: drag-drop, file validation, file list management
 */

import type { ComponentSchema, PropDef } from '@civui/schema/types';
import { toPascalCase, toComponentName } from '../utils/naming.js';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function litPropType(prop: PropDef): string {
  switch (prop.type) {
    case 'string': case 'enum': return 'String';
    case 'boolean': return 'Boolean';
    case 'number': return 'Number';
    case 'array': return 'Array';
    default: return 'String';
  }
}

function tsType(prop: PropDef, name: string, componentName: string): string {
  if (prop.type === 'enum' && prop.values) return `${componentName}${toComponentName(`-${name}`)}`;
  if (prop.type === 'array' && prop.items) return `${componentName}Option[]`;
  switch (prop.type) {
    case 'string': return 'string';
    case 'boolean': return 'boolean';
    case 'number': return 'number';
    case 'array': return 'unknown[]';
    default: return 'string';
  }
}

function defaultValue(prop: PropDef): string {
  if (prop.default === undefined) return '';
  if (Array.isArray(prop.default)) return ' = []';
  if (typeof prop.default === 'string') return ` = '${prop.default}'`;
  if (typeof prop.default === 'boolean') return ` = ${prop.default}`;
  if (typeof prop.default === 'number') return ` = ${prop.default}`;
  return '';
}

function generatePropDeclarations(schema: ComponentSchema): string {
  const componentName = toComponentName(schema.name);
  return Object.entries(schema.props)
    .map(([name, prop]) => {
      const type = tsType(prop, name, componentName);
      const litType = litPropType(prop);
      const def = defaultValue(prop);
      const optional = prop.default === undefined ? '?' : '';
      const reflectOpt = prop.reflect ? ', reflect: true' : '';
      const attrOpt = prop.attribute ? `, attribute: '${prop.attribute}'` : '';
      return `  @property({ type: ${litType}${reflectOpt}${attrOpt} }) ${name}${optional}: ${type}${def};`;
    })
    .join('\n');
}

function generateEnumTypes(schema: ComponentSchema): string {
  const lines: string[] = [];
  const componentName = toComponentName(schema.name);
  for (const [name, prop] of Object.entries(schema.props)) {
    if (prop.type === 'enum' && prop.values) {
      const typeName = `${componentName}${toComponentName(`-${name}`)}`;
      const union = prop.values.map((v) => `'${v}'`).join(' | ');
      lines.push(`export type ${typeName} = ${union};`);
    }
  }
  return lines.length > 0 ? lines.join('\n') + '\n' : '';
}

function header(schema: ComponentSchema): string {
  return `// Auto-generated by @civui/codegen — do not edit\n// Source: packages/schema/src/components/${schema.name}.schema.ts\n`;
}

function tagNameMap(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  return [
    '',
    'declare global {',
    '  interface HTMLElementTagNameMap {',
    `    '${schema.name}': ${className};`,
    '  }',
    '}',
    '',
  ].join('\n');
}

function jsdoc(schema: ComponentSchema): string {
  const componentName = toComponentName(schema.name);
  return [
    '/**',
    ` * CivUI ${componentName}`,
    ' *',
    ` * ${schema.description}`,
    ' *',
    ` * @element ${schema.name}`,
    ' */',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Textarea Generator
// ---------------------------------------------------------------------------

export function generateTextareaLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { CivFormElement, debounce, dispatch, renderLabel, renderHint, renderError, inputClasses } from '@civui/core';

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  @state() private _charCount = 0;
  @state() private _announcedCharCount = 0;

  private _charCountId = this.generateId('charcount');
  private _debouncedAnnounceCount = debounce(() => {
    this._announcedCharCount = this._charCount;
  }, 1000);

  override connectedCallback(): void {
    super.connectedCallback();
    this._charCount = this.value?.length || 0;
    this._announcedCharCount = this._charCount;
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this._debouncedAnnounceCount.cancel();
  }

  protected override get _ariaDescribedBy(): string {
    const ids: string[] = [];
    if (this.hint) ids.push(this._hintId);
    if (this.error) ids.push(this._errorId);
    if (this.maxlength != null && this.maxlength > 0) ids.push(this._charCountId);
    return ids.join(' ') || '';
  }

  override render() {
    const classes = inputClasses({
      extra: ['civ-resize-y'],
    });

    const showCharCount = this.maxlength != null && this.maxlength > 0;
    const remaining = showCharCount ? this.maxlength! - this._charCount : 0;

    return html\`
      <div class="civ-mb-4">
        \${renderLabel({ label: this.label, inputId: this._inputId, required: this.required })}
        \${renderHint(this._hintId, this.hint)}
        \${renderError(this._errorId, this.error)}
        <textarea
          class="\${classes}"
          id="\${this._inputId}"
          name="\${this.name}"
          rows="\${this.rows}"
          .value="\${this.value}"
          placeholder="\${this.placeholder || nothing}"
          maxlength="\${this.maxlength && this.maxlength > 0 ? this.maxlength : nothing}"
          ?disabled="\${this.disabled}"
          ?required="\${this.required}"
          aria-required="\${this.required || nothing}"
          aria-describedby="\${this._ariaDescribedBy || nothing}"
          aria-invalid="\${this.error ? 'true' : nothing}"
          @input="\${this._onInput}"
          @change="\${this._handleChange}"
        >\${nothing}</textarea>
        \${showCharCount
          ? html\`
              <span
                id="\${this._charCountId}"
                class="civ-block civ-mt-0.5 civ-text-sm \${remaining < 0
                  ? 'civ-text-error civ-font-bold'
                  : 'civ-text-muted'}"
              >
                \${remaining} characters remaining
              </span>
              <span class="civ-sr-only" aria-live="polite">
                \${this.maxlength! - this._announcedCharCount} characters remaining
              </span>
            \`
          : nothing}
      </div>
    \`;
  }

  override formResetCallback(): void {
    super.formResetCallback();
    this._charCount = this._defaultValue?.length || 0;
    this._announcedCharCount = this._charCount;
    this._debouncedAnnounceCount.cancel();
  }

  private _onInput(e: Event): void {
    const target = e.target as HTMLTextAreaElement;
    this.value = target.value;
    this._charCount = target.value.length;
    this._debouncedAnnounceCount();
    dispatch(this, 'civ-input', { value: this.value });
  }
}
${tagNameMap(schema)}`;
}

// ---------------------------------------------------------------------------
// Radio Group Generator
// ---------------------------------------------------------------------------

export function generateRadioGroupLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { CivFormElement, dispatch, renderLegend, renderHint, renderError, resolveGroupNavIndex, isRtl } from '@civui/core';
import type { CivRadio } from './civ-radio.js';

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  protected override _defaultValue = '';
  private _boundOnChildChange = this._onChildChange.bind(this);
  private _boundStopChildInput = this._stopChildInput.bind(this);
  private _boundOnKeydown = this._onKeydown.bind(this);

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.addEventListener('civ-input', this._boundStopChildInput as EventListener);
    this.addEventListener('keydown', this._boundOnKeydown as EventListener);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.removeEventListener('civ-input', this._boundStopChildInput as EventListener);
    this.removeEventListener('keydown', this._boundOnKeydown as EventListener);
  }

  protected override willUpdate(changed: Map<string, unknown>): void {
    super.willUpdate(changed);
    if (changed.has('legend')) {
      this.label = this.legend;
    }
  }

  override firstUpdated(): void {
    this._syncRadioNames();
    if (this.value) {
      this._syncRadioChecked();
    } else {
      const checked = this._getRadios().find((r) => r.checked);
      if (checked) this.value = checked.value;
      this._syncRadioChecked();
    }
    this._syncTabindex();
    this._syncRadioRequired();
    this._syncRadioTile();
    this._defaultValue = this.value;
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (changed.has('name')) this._syncRadioNames();
    if (changed.has('value')) { this._syncRadioChecked(); this._syncTabindex(); }
    if (changed.has('error')) this._syncRadioError();
    if (changed.has('disabled')) this._syncRadioDisabled();
    if (changed.has('required')) this._syncRadioRequired();
    if (changed.has('tile')) this._syncRadioTile();
  }

  override formDisabledCallback(disabled: boolean): void {
    super.formDisabledCallback(disabled);
    this._syncRadioDisabled();
  }

  override render() {
    const layoutClass =
      this.orientation === 'horizontal'
        ? 'civ-group-layout--horizontal'
        : 'civ-group-layout--vertical';

    return html\`
      <fieldset
        class="civ-fieldset"
        role="radiogroup"
        aria-orientation="\${this.orientation}"
        aria-describedby="\${this._ariaDescribedBy || nothing}"
        aria-invalid="\${this.error ? 'true' : nothing}"
        aria-required="\${this.required || nothing}"
        ?disabled="\${this.disabled}"
      >
        \${renderLegend({ legend: this.legend, required: this.required })}
        \${renderHint(this._hintId, this.hint, true)}
        \${renderError(this._errorId, this.error, true)}
        <div class="\${layoutClass}"></div>
      </fieldset>
    \`;
  }

  private _getRadios(): CivRadio[] {
    return Array.from(this.querySelectorAll('civ-radio')) as CivRadio[];
  }

  private _getEnabledRadios(): CivRadio[] {
    return this._getRadios().filter((r) => !r.disabled);
  }

  private _syncRadioNames(): void {
    if (!this.name) return;
    this._getRadios().forEach((radio) => {
      radio.name = this.name;
      radio.disableAnalytics = true;
    });
  }

  private _syncRadioChecked(): void {
    this._getRadios().forEach((radio) => {
      radio.checked = radio.value === this.value;
    });
  }

  private _syncRadioError(): void {
    const hasError = !!this.error;
    this._getRadios().forEach((radio) => {
      radio.error = hasError ? this.error : '';
    });
  }

  private _groupDisabledSet = new WeakSet<Element>();

  private _syncRadioDisabled(): void {
    const radios = this._getRadios();
    if (this.disabled) {
      radios.forEach((radio) => {
        if (!radio.disabled) this._groupDisabledSet.add(radio);
        radio.disabled = true;
      });
    } else {
      radios.forEach((radio) => {
        if (this._groupDisabledSet.has(radio)) {
          radio.disabled = false;
        }
      });
      this._groupDisabledSet = new WeakSet();
    }
  }

  private _syncRadioRequired(): void {
    this._getRadios().forEach((radio) => {
      radio.required = this.required;
    });
  }

  private _syncRadioTile(): void {
    this._getRadios().forEach((radio) => {
      radio.tile = this.tile;
    });
  }

  private _syncTabindex(): void {
    const radios = this._getRadios();
    const checkedRadio = radios.find((r) => r.checked);
    const enabledRadios = radios.filter((r) => !r.disabled);
    const focusTarget =
      checkedRadio && !checkedRadio.disabled
        ? checkedRadio
        : enabledRadios[0];

    radios.forEach((radio) => {
      radio.managedTabIndex = radio === focusTarget ? 0 : -1;
    });
  }

  private _stopChildInput(e: Event): void {
    if (e.target !== this) e.stopPropagation();
  }

  private _onChildChange(e: Event): void {
    const detail = (e as CustomEvent).detail;
    if (detail?.value == null) return;
    if (e.target === this) return;

    this.value = detail.value;
    this.updateFormValue(this.value);
    this._syncRadioChecked();
    this._syncTabindex();

    e.stopPropagation();
    dispatch(this, 'civ-input', { value: this.value });
    dispatch(this, 'civ-change', { value: this.value });
    this.sendAnalytics('change');
  }

  private _onKeydown(e: KeyboardEvent): void {
    const radios = this._getEnabledRadios();
    if (radios.length === 0) return;

    const currentIndex = radios.findIndex((r) => r.checked);
    const nextIndex = resolveGroupNavIndex(e.key, currentIndex, radios.length, isRtl(this));

    if (nextIndex !== undefined) {
      e.preventDefault();
      const radio = radios[nextIndex];
      radio.checked = true;
      this.value = radio.value;
      this.updateFormValue(this.value);
      this._syncRadioChecked();
      this._syncTabindex();

      const input = radio.querySelector('input[type="radio"]') as HTMLInputElement | null;
      if (input) input.focus();
      this.announce(radio.label);

      dispatch(this, 'civ-input', { value: this.value });
      dispatch(this, 'civ-change', { value: this.value });
      this.sendAnalytics('change');
    }
  }

  protected override _syncFormValue(): void {
    this.updateFormValue(this.value || '');
  }

  override formResetCallback(): void {
    this.value = this._defaultValue;
    this.error = '';
    this._syncRadioChecked();
    this._syncTabindex();
    this.updateFormValue(this._defaultValue || '');
    dispatch(this, 'civ-reset');
  }
}
${tagNameMap(schema)}`;
}

// ---------------------------------------------------------------------------
// Checkbox Group Generator
// ---------------------------------------------------------------------------

export function generateCheckboxGroupLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { CivFormElement, dispatch, renderLegend, renderHint, renderError } from '@civui/core';
import type { CivCheckbox } from './civ-checkbox.js';

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  protected override _defaultValue = '';
  private _boundOnChildChange = this._onChildChange.bind(this);
  private _boundStopChildInput = this._stopChildInput.bind(this);

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.addEventListener('civ-input', this._boundStopChildInput as EventListener);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.removeEventListener('civ-input', this._boundStopChildInput as EventListener);
  }

  protected override willUpdate(changed: Map<string, unknown>): void {
    super.willUpdate(changed);
    if (changed.has('legend')) {
      this.label = this.legend;
    }
  }

  override firstUpdated(): void {
    this._syncCheckboxNames();
    this._syncCheckboxDisabled();
    this._syncCheckboxTile();

    if (this.value) {
      this._syncCheckboxChecked();
    } else {
      this._readCheckedFromChildren();
    }

    this._defaultValue = this.value;
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (changed.has('name')) this._syncCheckboxNames();
    if (changed.has('disabled')) this._syncCheckboxDisabled();
    if (changed.has('tile')) this._syncCheckboxTile();
    if (changed.has('value') && changed.get('value') !== undefined) this._syncCheckboxChecked();
  }

  protected override _syncFormValue(): void {
    this._updateGroupFormValue();
  }

  override formDisabledCallback(disabled: boolean): void {
    super.formDisabledCallback(disabled);
    this._syncCheckboxDisabled();
  }

  override render() {
    const layoutClass =
      this.orientation === 'horizontal'
        ? 'civ-group-layout--horizontal'
        : 'civ-group-layout--vertical';

    return html\`
      <fieldset
        class="civ-fieldset"
        aria-describedby="\${this._ariaDescribedBy || nothing}"
        aria-invalid="\${this.error ? 'true' : nothing}"
        aria-required="\${this.required || nothing}"
        ?disabled="\${this.disabled}"
      >
        \${renderLegend({ legend: this.legend, required: this.required })}
        \${renderHint(this._hintId, this.hint, true)}
        \${renderError(this._errorId, this.error, true)}
        <div class="\${layoutClass}"></div>
      </fieldset>
    \`;
  }

  getCheckedValues(): string[] {
    return this._parseValue(this.value);
  }

  private _getCheckboxes(): CivCheckbox[] {
    return Array.from(this.querySelectorAll('civ-checkbox')) as CivCheckbox[];
  }

  private _parseValue(val: string): string[] {
    return val
      ? val.split(',').map((v) => v.trim()).filter(Boolean)
      : [];
  }

  private _serializeValue(values: string[]): string {
    return values.join(',');
  }

  private _syncCheckboxNames(): void {
    this._getCheckboxes().forEach((cb) => {
      if (this.name) cb.name = this.name;
      cb.disableAnalytics = true;
    });
  }

  private _groupDisabledSet = new WeakSet<Element>();

  private _syncCheckboxDisabled(): void {
    const children = this._getCheckboxes();
    if (this.disabled) {
      children.forEach((cb) => {
        if (!cb.disabled) this._groupDisabledSet.add(cb);
        cb.disabled = true;
      });
    } else {
      children.forEach((cb) => {
        if (this._groupDisabledSet.has(cb)) {
          cb.disabled = false;
        }
      });
      this._groupDisabledSet = new WeakSet();
    }
  }

  private _syncCheckboxTile(): void {
    this._getCheckboxes().forEach((cb) => {
      cb.tile = this.tile;
    });
  }

  private _syncCheckboxChecked(): void {
    const selected = this._parseValue(this.value);
    this._getCheckboxes().forEach((cb) => {
      cb.checked = selected.includes(cb.value);
    });
  }

  private _readCheckedFromChildren(): void {
    const values: string[] = [];
    this._getCheckboxes().forEach((cb) => {
      if (cb.checked) values.push(cb.value);
    });
    this.value = this._serializeValue(values);
    this._updateGroupFormValue();
  }

  private _updateGroupFormValue(): void {
    const values = this._parseValue(this.value);
    if (values.length === 0) {
      this.updateFormValue(null);
      return;
    }
    const fd = new FormData();
    for (const v of values) {
      fd.append(this.name, v);
    }
    this.updateFormValue(fd);
  }

  private _stopChildInput(e: Event): void {
    if (e.target !== this) e.stopPropagation();
  }

  private _onChildChange(e: Event): void {
    if (e.target === this) return;
    e.stopPropagation();

    const values: string[] = [];
    this._getCheckboxes().forEach((cb) => {
      if (cb.checked) values.push(cb.value);
    });

    this.value = this._serializeValue(values);
    this._updateGroupFormValue();

    dispatch(this, 'civ-input', { values: this.getCheckedValues() });
    dispatch(this, 'civ-change', { values: this.getCheckedValues() });
    this.sendAnalytics('change');
  }

  override formResetCallback(): void {
    this.value = this._defaultValue;
    this.error = '';
    this._syncCheckboxChecked();
    this._updateGroupFormValue();
    dispatch(this, 'civ-reset');
  }
}
${tagNameMap(schema)}`;
}

// ---------------------------------------------------------------------------
// Segmented Control Generator
// ---------------------------------------------------------------------------

export function generateSegmentedLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { CivFormElement, dispatch, renderLegend, renderHint, renderError, resolveGroupNavIndex, isRtl } from '@civui/core';
import type { CivSegment } from './civ-segment.js';

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  protected override _defaultValue = '';
  private _boundOnChildChange = this._onChildChange.bind(this);
  private _boundStopChildInput = this._stopChildInput.bind(this);
  private _boundOnKeydown = this._onKeydown.bind(this);

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.addEventListener('civ-input', this._boundStopChildInput as EventListener);
    this.addEventListener('keydown', this._boundOnKeydown as EventListener);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('civ-change', this._boundOnChildChange as EventListener);
    this.removeEventListener('civ-input', this._boundStopChildInput as EventListener);
    this.removeEventListener('keydown', this._boundOnKeydown as EventListener);
  }

  override willUpdate(changed: Map<string, unknown>): void {
    super.willUpdate(changed);
    if (changed.has('legend')) {
      this.label = this.legend;
    }
  }

  override firstUpdated(): void {
    this._syncSegmentSelected();
    this._syncSegmentPositions();
    this._defaultValue = this.value;
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (changed.has('value')) {
      this._syncSegmentSelected();
      this._syncSegmentPositions();
    }
    if (changed.has('disabled')) {
      this._syncSegmentDisabled();
    }
  }

  override formDisabledCallback(disabled: boolean): void {
    this.disabled = disabled;
    this._syncSegmentDisabled();
  }

  override render() {
    return html\`
      <fieldset
        class="civ-fieldset"
        role="radiogroup"
        aria-orientation="horizontal"
        aria-describedby="\${this._ariaDescribedBy || nothing}"
        aria-invalid="\${this.error ? 'true' : nothing}"
        aria-required="\${this.required || nothing}"
        ?disabled="\${this.disabled}"
      >
        \${renderLegend({ legend: this.legend, required: this.required, srOnly: true })}
        \${renderHint(this._hintId, this.hint, true)}
        \${renderError(this._errorId, this.error, true)}
        <div class="civ-inline-flex"></div>
      </fieldset>
    \`;
  }

  private _getSegments(): CivSegment[] {
    return Array.from(this.querySelectorAll('civ-segment')) as CivSegment[];
  }

  private _getEnabledSegments(): CivSegment[] {
    return this._getSegments().filter((s) => !s.disabled);
  }

  private _syncSegmentSelected(): void {
    this._getSegments().forEach((segment) => {
      segment.selected = segment.value === this.value;
    });
  }

  private _groupDisabledSet = new WeakSet<Element>();

  private _syncSegmentDisabled(): void {
    const segments = this._getSegments();
    if (this.disabled) {
      segments.forEach((segment) => {
        if (!segment.disabled) this._groupDisabledSet.add(segment);
        segment.disabled = true;
      });
    } else {
      segments.forEach((segment) => {
        if (this._groupDisabledSet.has(segment)) {
          segment.disabled = false;
        }
      });
      this._groupDisabledSet = new WeakSet();
    }
  }

  private _syncSegmentPositions(): void {
    const segments = this._getSegments();
    segments.forEach((segment, i) => {
      let position: string;
      if (segments.length === 1) {
        position = 'only';
      } else if (i === 0) {
        position = 'first';
      } else if (i === segments.length - 1) {
        position = 'last';
      } else {
        position = 'middle';
      }
      segment.setAttribute('data-civ-segment-position', position);
    });
  }

  private _stopChildInput(e: Event): void {
    if (e.target !== this) e.stopPropagation();
  }

  private _onChildChange(e: Event): void {
    const detail = (e as CustomEvent).detail;
    if (detail?.value == null) return;
    if (e.target === this) return;
    if (this.value === detail.value) { e.stopPropagation(); return; }

    this.value = detail.value;
    this.updateFormValue(this.value);
    this._syncSegmentSelected();

    e.stopPropagation();
    dispatch(this, 'civ-input', { value: this.value });
    dispatch(this, 'civ-change', { value: this.value });
    this.sendAnalytics('change');
  }

  private _onKeydown(e: KeyboardEvent): void {
    const segments = this._getEnabledSegments();
    if (segments.length === 0) return;

    const currentIndex = segments.findIndex((s) => s.selected);
    const nextIndex = resolveGroupNavIndex(e.key, currentIndex, segments.length, isRtl(this));

    if (nextIndex !== undefined) {
      e.preventDefault();
      const segment = segments[nextIndex];
      if (segment.value === this.value) return;
      segment.selected = true;
      this.value = segment.value;
      this.updateFormValue(this.value);
      this._syncSegmentSelected();

      const btn = segment.querySelector('button');
      if (btn) btn.focus();
      this.announce(segment.label);

      dispatch(this, 'civ-input', { value: this.value });
      dispatch(this, 'civ-change', { value: this.value });
      this.sendAnalytics('change');
    }
  }

  override formResetCallback(): void {
    this.value = this._defaultValue;
    this.error = '';
    this._syncSegmentSelected();
    this.updateFormValue(this._defaultValue || '');
    dispatch(this, 'civ-reset');
  }
}
${tagNameMap(schema)}`;
}

// ---------------------------------------------------------------------------
// Date Picker Generator
// ---------------------------------------------------------------------------

export function generateDatePickerLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import {
  CivFormElement,
  createKeyboardHandler,
  trapFocus,
  generateCalendarMonth,
  getDayOfWeekHeaders,
  getMonthNames,
  parseISODate,
  toISODateString,
  formatDate,
  formatDateLong,
  parseDateString,
  isSameDay,
  addDays,
  addMonths,
  addYears,
  isDateDisabled,
  isMonthDisabled,
  clampDate,
  dispatch,
  interpolate,
  isRtl,
  renderLabel,
  renderHint,
  renderError,
  inputClasses,
  type CalendarDay,
  type DateConstraints,
} from '@civui/core';

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  @state() private _open = false;
  @state() private _focusedDate: Date = new Date();
  @state() private _displayMonth = this._focusedDate.getMonth();
  @state() private _displayYear = this._focusedDate.getFullYear();
  @state() private _inputValue = '';

  private _headingId = this.generateId('heading');
  private _gridId = this.generateId('grid');
  private _buttonId = this.generateId('btn');
  private _cleanupTrap: (() => void) | null = null;
  private _boundDocClick = this._onDocumentClick.bind(this);

  private get _constraints(): DateConstraints {
    return { min: this.min || undefined, max: this.max || undefined };
  }

  private _dialogKeyHandler = createKeyboardHandler([
    { key: 'Escape', handler: () => this._closeDialog() },
    { key: 'ArrowRight', handler: () => this._moveFocusSkipDisabled(isRtl(this) ? -1 : 1) },
    { key: 'ArrowLeft', handler: () => this._moveFocusSkipDisabled(isRtl(this) ? 1 : -1) },
    { key: 'ArrowDown', handler: () => this._moveFocusSkipDisabled(7) },
    { key: 'ArrowUp', handler: () => this._moveFocusSkipDisabled(-7) },
    {
      key: 'Home',
      handler: () => {
        const d = new Date(this._focusedDate);
        const day = d.getDay();
        const diff = (day - this.weekStartsOn + 7) % 7;
        this._moveFocus(addDays(d, -diff));
      },
    },
    {
      key: 'End',
      handler: () => {
        const d = new Date(this._focusedDate);
        const day = d.getDay();
        const weekEnd = (this.weekStartsOn + 6) % 7;
        const diff = (weekEnd - day + 7) % 7;
        this._moveFocus(addDays(d, diff));
      },
    },
    { key: 'PageDown', shiftKey: true, handler: () => this._moveFocus(addYears(this._focusedDate, 1)) },
    { key: 'PageUp', shiftKey: true, handler: () => this._moveFocus(addYears(this._focusedDate, -1)) },
    { key: 'PageDown', handler: () => this._moveFocus(addMonths(this._focusedDate, 1)) },
    { key: 'PageUp', handler: () => this._moveFocus(addMonths(this._focusedDate, -1)) },
    { key: 'Enter', handler: () => { if (!isDateDisabled(this._focusedDate, this._constraints)) this._selectDate(this._focusedDate); } },
    { key: ' ', handler: () => { if (!isDateDisabled(this._focusedDate, this._constraints)) this._selectDate(this._focusedDate); } },
  ]);

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener('click', this._boundDocClick);
    this._cleanupTrap?.();
  }

  override updated(changed: Map<string, unknown>): void {
    super.updated(changed);
    if (changed.has('value') && this.value) {
      const parsed = parseISODate(this.value);
      if (parsed) {
        this._inputValue = formatDate(parsed, this.locale);
        this._displayMonth = parsed.getMonth();
        this._displayYear = parsed.getFullYear();
        this._focusedDate = parsed;
      }
    }
    if (changed.has('_open') && this._open) {
      this._setupDialog();
    }
  }

  private _setupDialog(): void {
    requestAnimationFrame(() => {
      const dialog = this.querySelector('[data-civ-dialog]') as HTMLElement | null;
      if (!dialog) return;
      this._cleanupTrap?.();
      this._cleanupTrap = trapFocus(dialog);
      const target = dialog.querySelector<HTMLElement>('[data-civ-day][tabindex="0"]');
      target?.focus();
    });
  }

  override render() {
    const classes = inputClasses({ rounded: 'civ-rounded-s' });
    const selectedDate = this.value ? parseISODate(this.value) : null;
    const buttonLabel = selectedDate
      ? interpolate(this.selectedDateLabel, { date: formatDateLong(selectedDate, this.locale) })
      : this.chooseDateLabel;

    return html\`
      <div class="civ-mb-4 civ-relative">
        \${renderLabel({ label: this.label, inputId: this._inputId, required: this.required })}
        \${renderHint(this._hintId, this.hint)}
        \${renderError(this._errorId, this.error)}
        <div class="civ-flex civ-items-center">
          <input
            class="\${classes}"
            id="\${this._inputId}"
            type="text"
            .value="\${this._inputValue}"
            placeholder="\${this.placeholder}"
            ?disabled="\${this.disabled}"
            ?required="\${this.required}"
            aria-required="\${this.required || nothing}"
            aria-describedby="\${this._ariaDescribedBy || nothing}"
            aria-invalid="\${this.error ? 'true' : nothing}"
            @input="\${this._onTextInput}"
            @change="\${this._onTextChange}"
          />
          <button
            id="\${this._buttonId}"
            type="button"
            class="civ-datepicker-cal-btn hover:civ-bg-base-lighter"
            aria-label="\${buttonLabel}"
            aria-haspopup="dialog"
            aria-expanded="\${this._open}"
            aria-controls="\${this._open ? this._gridId : nothing}"
            ?disabled="\${this.disabled}"
            @click="\${this._toggleDialog}"
          >
            <svg aria-hidden="true" class="civ-w-5 civ-h-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
        \${this._open ? this._renderDialog(selectedDate) : nothing}
      </div>
    \`;
  }

  private _renderDialog(selectedDate: Date | null) {
    const cal = generateCalendarMonth(this._displayYear, this._displayMonth, {
      weekStartsOn: this.weekStartsOn,
    });
    const headers = getDayOfWeekHeaders(this.locale, this.weekStartsOn);
    const monthNames = getMonthNames(this.locale);
    const headingText = \`\${monthNames[this._displayMonth]} \${this._displayYear}\`;

    const prevMonthDisabled = isMonthDisabled(
      this._displayMonth === 0 ? this._displayYear - 1 : this._displayYear,
      this._displayMonth === 0 ? 11 : this._displayMonth - 1,
      this._constraints,
    );
    const nextMonthDisabled = isMonthDisabled(
      this._displayMonth === 11 ? this._displayYear + 1 : this._displayYear,
      this._displayMonth === 11 ? 0 : this._displayMonth + 1,
      this._constraints,
    );

    return html\`
      <div
        data-civ-dialog
        role="dialog"
        aria-modal="true"
        aria-label="\${this.dialogLabel}"
        class="civ-datepicker-dialog"
        @keydown="\${this._onDialogKeydown}"
      >
        <div class="civ-flex civ-items-center civ-justify-between civ-mb-2">
          <button
            type="button"
            class="civ-datepicker-nav-btn hover:civ-bg-base-lightest"
            aria-label="\${this.previousMonthLabel}"
            ?disabled="\${prevMonthDisabled}"
            @click="\${this._prevMonth}"
          >
            <svg aria-hidden="true" class="civ-w-5 civ-h-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
          </button>
          <div id="\${this._headingId}" class="civ-font-bold civ-text-body" aria-live="polite">
            \${headingText}
          </div>
          <button
            type="button"
            class="civ-datepicker-nav-btn hover:civ-bg-base-lightest"
            aria-label="\${this.nextMonthLabel}"
            ?disabled="\${nextMonthDisabled}"
            @click="\${this._nextMonth}"
          >
            <svg aria-hidden="true" class="civ-w-5 civ-h-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
        <table role="grid" id="\${this._gridId}" aria-labelledby="\${this._headingId}">
          <thead>
            <tr>
              \${headers.map(
                (h) => html\`<th scope="col" class="civ-p-1 civ-text-center civ-text-sm civ-font-normal">
                  <abbr title="\${h.long}">\${h.short}</abbr>
                </th>\`,
              )}
            </tr>
          </thead>
          <tbody>
            \${cal.weeks.map(
              (week) => html\`
                <tr>
                  \${week.map((day) => this._renderDayCell(day, selectedDate))}
                </tr>
              \`,
            )}
          </tbody>
        </table>
      </div>
    \`;
  }

  private _renderDayCell(day: CalendarDay, selectedDate: Date | null) {
    const disabled = !day.inCurrentMonth || isDateDisabled(day.date, this._constraints);
    const selected = selectedDate ? isSameDay(day.date, selectedDate) : false;
    const focused = isSameDay(day.date, this._focusedDate);
    const tabIdx = focused && day.inCurrentMonth ? 0 : -1;

    const extraClasses = [
      !day.inCurrentMonth ? 'civ-text-base-light' : '',
      !disabled ? 'hover:civ-bg-primary-lightest' : '',
      day.isToday && !selected ? 'civ-font-bold civ-underline' : '',
      selected ? 'focus-visible:civ-focus-ring-inverse' : '',
    ]
      .filter(Boolean)
      .join(' ');

    return html\`
      <td role="gridcell">
        <button
          type="button"
          data-civ-day
          data-date="\${toISODateString(day.date)}"
          class="civ-datepicker-day \${extraClasses}"
          tabindex="\${tabIdx}"
          aria-selected="\${selected}"
          aria-disabled="\${disabled}"
          aria-label="\${formatDateLong(day.date, this.locale)}\${day.isToday ? \`, \${this.todayLabel}\` : ''}"
          @click="\${() => !disabled && this._selectDate(day.date)}"
        >
          \${day.day}
        </button>
      </td>
    \`;
  }

  private _toggleDialog(): void {
    if (this.disabled) return;
    if (this._open) { this._closeDialog(); } else { this._openDialog(); }
  }

  private _openDialog(): void {
    const selected = this.value ? parseISODate(this.value) : null;
    const today = new Date();
    const initial = selected ?? today;
    this._focusedDate = initial;
    this._displayMonth = initial.getMonth();
    this._displayYear = initial.getFullYear();
    this._open = true;
    document.addEventListener('click', this._boundDocClick);
    this.announce(this.dialogOpenedMessage);
  }

  private _closeDialog(): void {
    this._open = false;
    document.removeEventListener('click', this._boundDocClick);
    this._cleanupTrap?.();
    this._cleanupTrap = null;
    requestAnimationFrame(() => {
      const btn = this.querySelector(\`#\${this._buttonId}\`) as HTMLElement | null;
      btn?.focus();
    });
  }

  private _selectDate(date: Date): void {
    const iso = toISODateString(date);
    this.value = iso;
    this._inputValue = formatDate(date, this.locale);
    this.updateFormValue(iso);
    dispatch(this, 'civ-change', { value: iso });
    this.sendAnalytics('change');
    this.announce(interpolate(this.dateSelectedMessage, { date: formatDateLong(date, this.locale) }));
    this._closeDialog();
  }

  private _onTextInput(e: Event): void {
    const target = e.target as HTMLInputElement;
    this._inputValue = target.value;
    dispatch(this, 'civ-input', { value: target.value });
  }

  private _onTextChange(e: Event): void {
    const target = e.target as HTMLInputElement;
    const text = target.value.trim();

    if (!text) {
      this.value = '';
      this._inputValue = '';
      this.updateFormValue('');
      dispatch(this, 'civ-change', { value: '' });
      this.sendAnalytics('change');
      return;
    }

    const parsed = parseDateString(text, this.locale);
    if (parsed) {
      if (isDateDisabled(parsed, this._constraints)) return;
      const iso = toISODateString(parsed);
      this.value = iso;
      this._inputValue = formatDate(parsed, this.locale);
      this._displayMonth = parsed.getMonth();
      this._displayYear = parsed.getFullYear();
      this._focusedDate = parsed;
      this.updateFormValue(iso);
      dispatch(this, 'civ-change', { value: iso });
      this.sendAnalytics('change');
      this.announce(interpolate(this.dateSelectedMessage, { date: formatDateLong(parsed, this.locale) }));
    } else {
      this.announce('Invalid date format', 'assertive');
    }
  }

  private _navigateMonth(delta: number): void {
    const newMonth = this._displayMonth + delta;
    if (newMonth < 0) {
      this._displayMonth = 11;
      this._displayYear--;
    } else if (newMonth > 11) {
      this._displayMonth = 0;
      this._displayYear++;
    } else {
      this._displayMonth = newMonth;
    }
    this._focusedDate = new Date(this._displayYear, this._displayMonth, 1);
    const monthNames = getMonthNames(this.locale);
    this.announce(\`\${monthNames[this._displayMonth]} \${this._displayYear}\`);
  }

  private _prevMonth(): void { this._navigateMonth(-1); }
  private _nextMonth(): void { this._navigateMonth(1); }

  private _moveFocus(newDate: Date): void {
    if (newDate.getMonth() !== this._displayMonth || newDate.getFullYear() !== this._displayYear) {
      this._displayMonth = newDate.getMonth();
      this._displayYear = newDate.getFullYear();
    }
    this._focusedDate = newDate;
    this.updateComplete.then(() => {
      const iso = toISODateString(newDate);
      const btn = this.querySelector(\`[data-date="\${iso}"]\`) as HTMLElement | null;
      btn?.focus();
      this.announce(formatDateLong(newDate, this.locale));
    });
  }

  private _moveFocusSkipDisabled(days: number): void {
    const direction = days > 0 ? 1 : -1;
    let candidate = addDays(this._focusedDate, days);
    const maxAttempts = 31;
    for (let i = 0; i < maxAttempts; i++) {
      if (!isDateDisabled(candidate, this._constraints)) {
        this._moveFocus(candidate);
        return;
      }
      candidate = addDays(candidate, direction);
    }
    if (this._constraints.min || this._constraints.max) {
      const clamped = clampDate(this._focusedDate, this._constraints);
      if (!isDateDisabled(clamped, this._constraints)) {
        this._moveFocus(clamped);
      }
    }
  }

  private _onDialogKeydown(e: KeyboardEvent): void {
    this._dialogKeyHandler(e);
  }

  private _onDocumentClick(e: MouseEvent): void {
    const path = e.composedPath();
    if (!path.includes(this)) {
      this._closeDialog();
    }
  }

  override formResetCallback(): void {
    this.value = this._defaultValue;
    const initial = this._defaultValue ? parseISODate(this._defaultValue) : null;
    this._inputValue = initial ? formatDate(initial, this.locale) : '';
    this._open = false;
    this.error = '';
    const fallback = initial || new Date();
    this._focusedDate = fallback;
    this._displayMonth = fallback.getMonth();
    this._displayYear = fallback.getFullYear();
    this.updateFormValue(this._defaultValue || '');
    dispatch(this, 'civ-reset');
  }
}
${tagNameMap(schema)}`;
}

// ---------------------------------------------------------------------------
// File Upload Generator
// ---------------------------------------------------------------------------

export function generateFileUploadLit(schema: ComponentSchema): string {
  const className = toPascalCase(schema.name);
  const propDecls = generatePropDeclarations(schema);
  const enumTypes = generateEnumTypes(schema);

  return `${header(schema)}
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { CivFormElement, dispatch, interpolate, renderLabel, renderHint, renderError } from '@civui/core';

interface UploadedFile {
  name: string;
  size: number;
  type: string;
  file: File;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return \`\${bytes} B\`;
  if (bytes < 1024 * 1024) return \`\${(bytes / 1024).toFixed(1)} KB\`;
  return \`\${(bytes / (1024 * 1024)).toFixed(1)} MB\`;
}

${enumTypes}${jsdoc(schema)}
@customElement('${schema.name}')
export class ${className} extends CivFormElement {
${propDecls}

  @state() private _files: UploadedFile[] = [];
  @state() private _dragging = false;

  private _boundDragOver = this._onDragOver.bind(this);
  private _boundDragLeave = this._onDragLeave.bind(this);
  private _boundDrop = this._onDrop.bind(this);

  get files(): File[] {
    return this._files.map((f) => f.file);
  }

  override render() {
    return html\`
      <div class="civ-mb-4">
        \${renderLabel({ label: this.label, inputId: this._inputId, required: this.required })}
        \${renderHint(this._hintId, this.hint)}
        \${renderError(this._errorId, this.error)}

        <div
          class="civ-dropzone"
          @dragover="\${this._boundDragOver}"
          @dragleave="\${this._boundDragLeave}"
          @drop="\${this._boundDrop}"
          @click="\${this._onDropzoneClick}"
          role="button"
          tabindex="\${this.disabled ? '-1' : '0'}"
          aria-label="\${this.label}"
          aria-required="\${this.required || nothing}"
          aria-invalid="\${this.error ? 'true' : nothing}"
          aria-disabled="\${this.disabled || nothing}"
          aria-describedby="\${this._ariaDescribedBy || nothing}"
          @keydown="\${this._onDropzoneKeydown}"
          data-dragging="\${this._dragging || nothing}"
        >
          <span class="civ-block civ-text-body" style="color: var(--civ-color-base-dark)">
            \${this.dragText}
            <span class="civ-text-primary civ-underline">\${this.browseText}</span>
          </span>
          \${this.accept
            ? html\`<span class="civ-block civ-text-sm civ-text-muted civ-mt-1">\${this.acceptedLabel}\${this.accept}</span>\`
            : nothing}
          \${this.maxSize > 0
            ? html\`<span class="civ-block civ-text-sm civ-text-muted civ-mt-0.5">\${this.maxSizeLabel}\${formatFileSize(this.maxSize)}</span>\`
            : nothing}
        </div>

        <input
          id="\${this._inputId}"
          type="file"
          name="\${this.name}"
          accept="\${this.accept || nothing}"
          ?multiple="\${this.multiple}"
          ?disabled="\${this.disabled}"
          ?required="\${this.required && this._files.length === 0}"
          class="civ-hidden"
          @change="\${this._onFileSelect}"
          aria-hidden="true"
          tabindex="-1"
        />

        \${this._files.length > 0
          ? html\`
              <ul class="civ-list-none civ-p-0 civ-mt-2 civ-space-y-1" aria-label="\${this.filesListLabel}">
                \${this._files.map(
                  (file, index) => html\`
                    <li class="civ-list-item">
                      <span>
                        <span class="civ-font-semibold">\${file.name}</span>
                        <span class="civ-ms-2">(\${formatFileSize(file.size)})</span>
                      </span>
                      <button
                        type="button"
                        data-file-remove
                        @click="\${() => this._removeFile(index)}"
                        aria-label="\${interpolate(this.removeAriaLabel, { name: file.name })}"
                        ?disabled="\${this.disabled}"
                      >
                        \${this.removeText}
                      </button>
                    </li>
                  \`,
                )}
              </ul>
            \`
          : nothing}
      </div>
    \`;
  }

  protected override _syncFormValue(): void {
    // File upload manages its own FormData via _updateFormData()
  }

  private _onDropzoneClick(): void {
    if (this.disabled) return;
    const input = this.querySelector(\`#\${this._inputId}\`) as HTMLInputElement;
    input?.click();
  }

  private _onDropzoneKeydown(e: KeyboardEvent): void {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      this._onDropzoneClick();
    }
  }

  private _onDragOver(e: DragEvent): void {
    e.preventDefault();
    if (!this.disabled) this._dragging = true;
  }

  private _onDragLeave(): void {
    this._dragging = false;
  }

  private _onDrop(e: DragEvent): void {
    e.preventDefault();
    this._dragging = false;
    if (this.disabled || !e.dataTransfer) return;
    this._addFiles(Array.from(e.dataTransfer.files));
  }

  private _onFileSelect(e: Event): void {
    const input = e.target as HTMLInputElement;
    if (!input.files) return;
    this._addFiles(Array.from(input.files));
    input.value = '';
  }

  private _isFileTypeAccepted(file: File): boolean {
    if (!this.accept) return true;
    const accepted = this.accept.split(',').map((s) => s.trim().toLowerCase());
    const fileName = file.name.toLowerCase();
    const fileType = file.type.toLowerCase();

    return accepted.some((pattern) => {
      if (pattern.startsWith('.')) return fileName.endsWith(pattern);
      if (pattern.endsWith('/*')) return fileType.startsWith(pattern.slice(0, -1));
      return fileType === pattern;
    });
  }

  private _addFiles(newFiles: File[]): void {
    const validated: UploadedFile[] = [];
    const errors: string[] = [];

    for (const file of newFiles) {
      if (this.accept && !this._isFileTypeAccepted(file)) {
        errors.push(interpolate(this.fileTypeError, { name: file.name }));
        continue;
      }
      if (this.maxSize > 0 && file.size > this.maxSize) {
        errors.push(interpolate(this.fileSizeError, { name: file.name, size: formatFileSize(this.maxSize) }));
        continue;
      }
      validated.push({ name: file.name, size: file.size, type: file.type, file });
    }

    if (this.maxFiles > 0 && this.multiple) {
      const available = this.maxFiles - this._files.length;
      if (validated.length > available) {
        validated.splice(available);
        errors.push(interpolate(this.maxFilesError, { max: this.maxFiles }));
      }
    }

    if (errors.length > 0) {
      this.error = errors.join('. ');
    }

    if (validated.length === 0) return;
    if (errors.length === 0) this.error = '';

    if (this.multiple) {
      this._files = [...this._files, ...validated];
    } else {
      this._files = validated.slice(0, 1);
    }

    this._updateFormData();
    this._dispatchChange();
    this.sendAnalytics('upload', { fileCount: this._files.length });
    this.announce(interpolate(this.fileAddedMessage, { count: validated.length, total: this._files.length }));
  }

  private _removeFile(index: number): void {
    this._files = this._files.filter((_, i) => i !== index);
    if (this._files.length === 0) this.error = '';
    this._updateFormData();
    this._dispatchChange();
    this.sendAnalytics('remove', { fileCount: this._files.length });
    this.announce(interpolate(this.fileRemovedMessage, { total: this._files.length }));

    this.updateComplete.then(() => {
      const buttons = this.querySelectorAll<HTMLButtonElement>('[data-file-remove]');
      if (buttons.length > 0) {
        const next = buttons[Math.min(index, buttons.length - 1)];
        next.focus();
      } else {
        const dropzone = this.querySelector<HTMLElement>('.civ-dropzone');
        dropzone?.focus();
      }
    });
  }

  private _updateFormData(): void {
    if (this._files.length === 0) {
      this.value = '';
      this.updateFormValue(null);
    } else {
      this.value = this._files.map((f) => f.name).join(', ');
      const formData = new FormData();
      for (const f of this._files) {
        formData.append(this.name || 'file', f.file);
      }
      this.updateFormValue(formData);
    }
  }

  private _dispatchChange(): void {
    const files = this._files.map((f) => f.file);
    dispatch(this, 'civ-input', { files });
    dispatch(this, 'civ-change', { files });
  }

  override formResetCallback(): void {
    this._files = [];
    this.value = '';
    this.error = '';
    this.updateFormValue(null);
    const input = this.querySelector(\`#\${this._inputId}\`) as HTMLInputElement | null;
    if (input) input.value = '';
    dispatch(this, 'civ-reset');
  }
}
${tagNameMap(schema)}`;
}
