import { describe, it, expect } from 'vitest';
import { generateSwiftUI } from './swiftui.js';
import type { ComponentSchema } from '@civui/schema/types';

// Reusable minimal schemas

function makeSchema(overrides: Partial<ComponentSchema> & { name: string }): ComponentSchema {
  return {
    $schema: '1.0',
    description: 'Test component',
    category: 'form-control',
    extends: 'CivFormElement',
    isGroup: false,
    props: {},
    events: {},
    a11y: { role: 'textbox', requiredIndicator: 'asterisk', errorAnnouncement: 'assertive' },
    renderOrder: [],
    form: { valueMode: 'string', formAssociated: true, resetBehavior: 'restore-default-value' },
    ...overrides,
  };
}

describe('SwiftUI generator', () => {
  describe('text input pattern', () => {
    const schema = makeSchema({
      name: 'civ-text-input',
      props: {
        type: { type: 'enum', description: 'Type', default: 'text', values: ['text', 'email', 'password'] },
        placeholder: { type: 'string', description: 'Placeholder', default: '' },
      },
      widths: {
        default: { webClass: 'civ-w-full', iosPoints: null, androidDp: null },
        sm: { webClass: 'civ-w-24', iosPoints: 96, androidDp: 96 },
      },
      platform: {
        ios: {
          keyboardType: { text: '.default', email: '.emailAddress', password: '.default' },
          contentType: { email: '.emailAddress', password: '.password' },
          autocapitalization: { email: '.never', _default: '.sentences' },
        },
      },
    });
    const output = generateSwiftUI(schema);

    it('generates auto-generated header', () => {
      expect(output).toContain('// Auto-generated by @civui/codegen');
    });

    it('generates SwiftUI struct', () => {
      expect(output).toContain('public struct CivTextInput: View');
    });

    it('generates CivInputType enum', () => {
      expect(output).toContain('public enum CivInputType');
      expect(output).toContain('case text');
      expect(output).toContain('case email');
    });

    it('generates CivInputWidth enum with points', () => {
      expect(output).toContain('public enum CivInputWidth');
      expect(output).toContain('var points: CGFloat?');
      expect(output).toContain('return 96');
    });

    it('includes @Binding for value', () => {
      expect(output).toContain('@Binding public var value: String');
    });

    it('includes keyboard type mapping', () => {
      expect(output).toContain('private var keyboardType: UIKeyboardType');
      expect(output).toContain('.emailAddress');
    });

    it('includes content type mapping', () => {
      expect(output).toContain('private var contentType: UITextContentType?');
    });

    it('generates TextField and SecureField', () => {
      expect(output).toContain('TextField(');
      expect(output).toContain('SecureField(');
    });

    it('includes accessibility helpers', () => {
      expect(output).toContain('accessibilityLabelText');
      expect(output).toContain('accessibilityHintText');
    });

    it('includes colorScheme environment', () => {
      expect(output).toContain('@Environment(\\.colorScheme)');
    });

    it('generates preview', () => {
      expect(output).toContain('CivTextInput_Previews: PreviewProvider');
      expect(output).toContain('#if DEBUG');
    });
  });

  describe('checkbox pattern', () => {
    const schema = makeSchema({
      name: 'civ-checkbox',
      props: {
        checked: { type: 'boolean', description: 'Checked', default: false, reflect: true },
        description: { type: 'string', description: 'Description', default: '' },
        tile: { type: 'boolean', description: 'Tile', default: false },
      },
      a11y: { role: 'checkbox', requiredIndicator: 'asterisk', errorAnnouncement: 'assertive' },
      form: { valueMode: 'boolean', formAssociated: true, resetBehavior: 'restore-default-checked' },
    });
    const output = generateSwiftUI(schema);

    it('generates @Binding for checked Bool', () => {
      expect(output).toContain('@Binding public var checked: Bool');
    });

    it('uses Toggle with .checkbox style', () => {
      expect(output).toContain('Toggle(isOn: checkedBinding)');
      expect(output).toContain('.toggleStyle(.checkbox)');
    });

    it('generates checkedBinding helper', () => {
      expect(output).toContain('private var checkedBinding: Binding<Bool>');
    });

    it('has onCheckedChange callback', () => {
      expect(output).toContain('onCheckedChange: ((Bool) -> Void)?');
    });
  });

  describe('toggle pattern', () => {
    const schema = makeSchema({
      name: 'civ-toggle',
      props: {
        checked: { type: 'boolean', description: 'On state', default: false, reflect: true },
        description: { type: 'string', description: 'Description', default: '' },
      },
      a11y: { role: 'switch', requiredIndicator: 'asterisk', errorAnnouncement: 'assertive' },
      form: { valueMode: 'boolean', formAssociated: true, resetBehavior: 'restore-default-checked' },
    });
    const output = generateSwiftUI(schema);

    it('uses Toggle with .switch style', () => {
      expect(output).toContain('.toggleStyle(.switch)');
    });

    it('renders switch before label (inline layout)', () => {
      const switchIdx = output.indexOf('.toggleStyle(.switch)');
      const labelIdx = output.indexOf('Text(label)');
      expect(switchIdx).toBeLessThan(labelIdx);
    });
  });

  describe('select pattern', () => {
    const schema = makeSchema({
      name: 'civ-select',
      props: {
        options: {
          type: 'array', description: 'Options', default: [],
          items: { value: { type: 'string', description: 'Value', required: true }, label: { type: 'string', description: 'Label', required: true } },
        },
        emptyLabel: { type: 'string', description: 'Empty label', default: '- Select -' },
      },
    });
    const output = generateSwiftUI(schema);

    it('generates CivOption struct', () => {
      expect(output).toContain('public struct CivOption: Identifiable, Hashable');
    });

    it('uses Picker with .menu style', () => {
      expect(output).toContain('Picker(label, selection: $value)');
      expect(output).toContain('.pickerStyle(.menu)');
    });

    it('renders ForEach over options', () => {
      expect(output).toContain('ForEach(options)');
    });
  });

  describe('radio group pattern', () => {
    const schema = makeSchema({
      name: 'civ-radio-group',
      isGroup: true,
      category: 'form-group',
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
        orientation: { type: 'enum', description: 'Orientation', default: 'vertical', values: ['vertical', 'horizontal'] },
      },
      a11y: { role: 'radiogroup', requiredIndicator: 'asterisk', errorAnnouncement: 'assertive' },
    });
    const output = generateSwiftUI(schema);

    it('uses legend as label prop', () => {
      expect(output).toContain('public let legend: String');
    });

    it('generates CivOrientation enum', () => {
      expect(output).toContain('public enum CivOrientation');
      expect(output).toContain('case vertical');
      expect(output).toContain('case horizontal');
    });

    it('has ViewBuilder content slot', () => {
      expect(output).toContain('content: () -> AnyView');
    });

    it('uses layout based on orientation', () => {
      expect(output).toContain('orientation == .horizontal');
    });
  });

  describe('date picker pattern', () => {
    const schema = makeSchema({
      name: 'civ-date-picker',
      props: {
        min: { type: 'string', description: 'Min date', default: '' },
        max: { type: 'string', description: 'Max date', default: '' },
        placeholder: { type: 'string', description: 'Placeholder', default: 'mm/dd/yyyy' },
      },
    });
    const output = generateSwiftUI(schema);

    it('uses native DatePicker', () => {
      expect(output).toContain('DatePicker(');
      expect(output).toContain('.datePickerStyle(.compact)');
    });

    it('generates dateBinding helper', () => {
      expect(output).toContain('private var dateBinding: Binding<Date>');
    });

    it('generates dateRange computed property', () => {
      expect(output).toContain('private var dateRange: ClosedRange<Date>');
    });
  });

  describe('segmented control pattern', () => {
    const schema = makeSchema({
      name: 'civ-segmented-control',
      isGroup: true,
      category: 'form-group',
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
      },
      a11y: { role: 'radiogroup', requiredIndicator: 'none', errorAnnouncement: 'assertive' },
    });
    const output = generateSwiftUI(schema);

    it('uses Picker with .segmented style', () => {
      expect(output).toContain('.pickerStyle(.segmented)');
    });
  });

  describe('form container pattern', () => {
    const schema = makeSchema({
      name: 'civ-form',
      extends: 'CivBaseElement',
      props: {
        formLabel: { type: 'string', description: 'Form label', default: '' },
      },
      form: { valueMode: 'string', formAssociated: false, resetBehavior: 'restore-default-value' },
    });
    const output = generateSwiftUI(schema);

    it('generates simple VStack container', () => {
      expect(output).toContain('VStack(');
      expect(output).toContain('content()');
    });

    it('has accessibility label', () => {
      expect(output).toContain('.accessibilityLabel(');
    });
  });

  describe('fieldset pattern', () => {
    const schema = makeSchema({
      name: 'civ-fieldset',
      extends: 'CivBaseElement',
      isGroup: true,
      props: {
        legend: { type: 'string', description: 'Legend', default: '' },
        hint: { type: 'string', description: 'Hint', default: '' },
        error: { type: 'string', description: 'Error', default: '' },
        required: { type: 'boolean', description: 'Required', default: false },
        disabled: { type: 'boolean', description: 'Disabled', default: false },
      },
      form: { valueMode: 'string', formAssociated: false, resetBehavior: 'restore-default-value' },
    });
    const output = generateSwiftUI(schema);

    it('applies disabled opacity', () => {
      expect(output).toContain('.disabled(isDisabled)');
      expect(output).toContain('.opacity(isDisabled ? 0.5 : 1.0)');
    });
  });
});
