// Auto-generated by @civui/tokens — do not edit

import SwiftUI

// MARK: - CivTokens

/// CivUI design tokens for SwiftUI.
/// Government design system — WCAG AA accessible, Section 508 compliant.
public enum CivTokens {

    // MARK: Colors

    public enum Colors {
        public enum Primary {
            public static let lightest = Color(red: 0.851, green: 0.91, blue: 0.965)
            public static let lighter = Color(red: 0.451, green: 0.702, blue: 0.906)
            public static let light = Color(red: 0.137, green: 0.471, blue: 0.765)
            public static let default_ = Color(red: 0, green: 0.369, blue: 0.635)
            public static let vivid = Color(red: 0, green: 0.314, blue: 0.847)
            public static let dark = Color(red: 0.102, green: 0.267, blue: 0.502)
            public static let darker = Color(red: 0.086, green: 0.18, blue: 0.318)
        }
        public enum Error {
            public static let lighter = Color(red: 0.957, green: 0.89, blue: 0.859)
            public static let light = Color(red: 0.839, green: 0.243, blue: 0.016)
            public static let default_ = Color(red: 0.71, green: 0.035, blue: 0.035)
            public static let dark = Color(red: 0.545, green: 0.039, blue: 0.012)
        }
        public enum Warning {
            public static let lighter = Color(red: 0.98, green: 0.953, blue: 0.82)
            public static let light = Color(red: 0.996, green: 0.902, blue: 0.522)
            public static let default_ = Color(red: 0.898, green: 0.627, blue: 0)
            public static let dark = Color(red: 0.576, green: 0.435, blue: 0.22)
        }
        public enum Success {
            public static let lighter = Color(red: 0.925, green: 0.953, blue: 0.925)
            public static let light = Color(red: 0.439, green: 0.882, blue: 0.482)
            public static let default_ = Color(red: 0, green: 0.663, blue: 0.11)
            public static let dark = Color(red: 0.302, green: 0.502, blue: 0.333)
        }
        public enum Info {
            public static let lighter = Color(red: 0.906, green: 0.965, blue: 0.973)
            public static let light = Color(red: 0.6, green: 0.871, blue: 0.918)
            public static let default_ = Color(red: 0, green: 0.741, blue: 0.89)
            public static let dark = Color(red: 0.18, green: 0.384, blue: 0.463)
        }
        public enum Base {
            public static let lightest = Color(red: 0.941, green: 0.941, blue: 0.941)
            public static let lighter = Color(red: 0.875, green: 0.882, blue: 0.886)
            public static let light = Color(red: 0.663, green: 0.682, blue: 0.694)
            public static let default_ = Color(red: 0.443, green: 0.463, blue: 0.478)
            public static let dark = Color(red: 0.337, green: 0.361, blue: 0.396)
            public static let darker = Color(red: 0.239, green: 0.271, blue: 0.318)
            public static let darkest = Color(red: 0.106, green: 0.106, blue: 0.106)
        }
        public enum White {
            public static let default_ = Color(red: 1, green: 1, blue: 1)
        }
        public enum Black {
            public static let default_ = Color(red: 0, green: 0, blue: 0)
        }
        public enum Accent {
            public enum Cool {
                public static let lightest = Color(red: 0.882, green: 0.953, blue: 0.973)
                public static let light = Color(red: 0.592, green: 0.831, blue: 0.918)
                public static let default_ = Color(red: 0, green: 0.741, blue: 0.89)
                public static let dark = Color(red: 0.157, green: 0.627, blue: 0.796)
            }
            public enum Warm {
                public static let lightest = Color(red: 0.949, green: 0.894, blue: 0.831)
                public static let light = Color(red: 1, green: 0.737, blue: 0.471)
                public static let default_ = Color(red: 0.98, green: 0.58, blue: 0.255)
                public static let dark = Color(red: 0.753, green: 0.337, blue: 0)
            }
        }
    }

    // MARK: Dark Colors

    public enum DarkColors {
        public enum Primary {
            public static let lightest = Color(red: 0.102, green: 0.227, blue: 0.361)
            public static let lighter = Color(red: 0.18, green: 0.424, blue: 0.659)
            public static let light = Color(red: 0.353, green: 0.639, blue: 0.91)
            public static let default_ = Color(red: 0.451, green: 0.702, blue: 0.906)
            public static let vivid = Color(red: 0.369, green: 0.655, blue: 0.961)
            public static let dark = Color(red: 0.643, green: 0.808, blue: 0.957)
            public static let darker = Color(red: 0.816, green: 0.894, blue: 0.973)
        }
        public enum Error {
            public static let lighter = Color(red: 0.29, green: 0.125, blue: 0.125)
            public static let light = Color(red: 0.91, green: 0.455, blue: 0.38)
            public static let default_ = Color(red: 0.949, green: 0.545, blue: 0.51)
            public static let dark = Color(red: 0.961, green: 0.718, blue: 0.694)
        }
        public enum Warning {
            public static let lighter = Color(red: 0.29, green: 0.239, blue: 0.102)
            public static let light = Color(red: 0.961, green: 0.835, blue: 0.463)
            public static let default_ = Color(red: 0.961, green: 0.773, blue: 0.259)
            public static let dark = Color(red: 0.788, green: 0.635, blue: 0.302)
        }
        public enum Success {
            public static let lighter = Color(red: 0.118, green: 0.227, blue: 0.125)
            public static let light = Color(red: 0.506, green: 0.847, blue: 0.541)
            public static let default_ = Color(red: 0.361, green: 0.722, blue: 0.361)
            public static let dark = Color(red: 0.494, green: 0.788, blue: 0.494)
        }
        public enum Info {
            public static let lighter = Color(red: 0.102, green: 0.227, blue: 0.251)
            public static let light = Color(red: 0.49, green: 0.827, blue: 0.878)
            public static let default_ = Color(red: 0.302, green: 0.816, blue: 0.882)
            public static let dark = Color(red: 0.502, green: 0.871, blue: 0.918)
        }
        public enum Base {
            public static let lightest = Color(red: 0.176, green: 0.176, blue: 0.176)
            public static let lighter = Color(red: 0.239, green: 0.239, blue: 0.239)
            public static let light = Color(red: 0.541, green: 0.541, blue: 0.541)
            public static let default_ = Color(red: 0.627, green: 0.627, blue: 0.627)
            public static let dark = Color(red: 0.769, green: 0.769, blue: 0.769)
            public static let darker = Color(red: 0.878, green: 0.878, blue: 0.878)
            public static let darkest = Color(red: 0.941, green: 0.941, blue: 0.941)
        }
        public enum White {
            public static let default_ = Color(red: 0.106, green: 0.106, blue: 0.106)
        }
        public enum Black {
            public static let default_ = Color(red: 1, green: 1, blue: 1)
        }
        public enum Accent {
            public enum Cool {
                public static let lightest = Color(red: 0.102, green: 0.227, blue: 0.251)
                public static let light = Color(red: 0.42, green: 0.773, blue: 0.847)
                public static let default_ = Color(red: 0.302, green: 0.816, blue: 0.882)
                public static let dark = Color(red: 0.502, green: 0.871, blue: 0.918)
            }
            public enum Warm {
                public static let lightest = Color(red: 0.239, green: 0.176, blue: 0.102)
                public static let light = Color(red: 0.961, green: 0.722, blue: 0.478)
                public static let default_ = Color(red: 0.961, green: 0.651, blue: 0.329)
                public static let dark = Color(red: 0.91, green: 0.573, blue: 0.29)
            }
        }
    }

    // MARK: Adaptive Colors

    /// Returns the appropriate color for the current color scheme.
    public static func color(_ light: Color, dark: Color, colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? dark : light
    }

    // MARK: Spacing

    public enum Spacing {
        public static let _0: CGFloat = 0
        public static let _1: CGFloat = 4
        public static let _2: CGFloat = 8
        public static let _3: CGFloat = 12
        public static let _4: CGFloat = 16
        public static let _5: CGFloat = 20
        public static let _6: CGFloat = 24
        public static let _8: CGFloat = 32
        public static let _10: CGFloat = 40
        public static let _12: CGFloat = 48
        public static let _16: CGFloat = 64
        public static let _20: CGFloat = 80
        public static let px: CGFloat = 1
        public static let _0_5: CGFloat = 2
        public static let _1_5: CGFloat = 6
        public static let _2_5: CGFloat = 10
    }

    // MARK: Typography

    public enum Typography {
        public enum FontFamily {
            public static let sans = ".AppleSystemUIFont"
            public static let mono = "Roboto Mono"
        }

        public enum FontSize {
            public static let xs: CGFloat = 12
            public static let sm: CGFloat = 14
            public static let base: CGFloat = 16
            public static let lg: CGFloat = 18
            public static let xl: CGFloat = 20
            public static let _2xl: CGFloat = 24
            public static let _3xl: CGFloat = 28
            public static let _4xl: CGFloat = 36
            public static let _5xl: CGFloat = 48
        }

        public enum FontWeight {
            public static let light: Font.Weight = .light
            public static let regular: Font.Weight = .regular
            public static let semibold: Font.Weight = .semibold
            public static let bold: Font.Weight = .bold
        }

        public enum LineHeight {
            public static let none: CGFloat = 1
            public static let tight: CGFloat = 1.25
            public static let snug: CGFloat = 1.375
            public static let normal: CGFloat = 1.5
            public static let relaxed: CGFloat = 1.625
            public static let loose: CGFloat = 2
        }
    }

    // MARK: Border

    public enum Border {
        public enum Radius {
            public static let none: CGFloat = 0
            public static let sm: CGFloat = 2
            public static let default_: CGFloat = 4
            public static let md: CGFloat = 6
            public static let lg: CGFloat = 8
            public static let full: CGFloat = 9999
        }

        public enum Width {
            public static let _0: CGFloat = 0
            public static let _2: CGFloat = 2
            public static let _4: CGFloat = 4
            public static let default_: CGFloat = 1
        }
    }

    // MARK: Shadow

    public struct ShadowValue {
        public let x: CGFloat
        public let y: CGFloat
        public let blur: CGFloat
        public let color: Color
    }

    public enum Shadow {
        public static let none = ShadowValue(x: 0, y: 0, blur: 0, color: .clear)
        public static let sm = ShadowValue(x: 0, y: 1, blur: 2, color: .black.opacity(0.1))
        public static let default_ = ShadowValue(x: 0, y: 1, blur: 3, color: .black.opacity(0.1))
        public static let md = ShadowValue(x: 0, y: 4, blur: 6, color: .black.opacity(0.1))
        public static let lg = ShadowValue(x: 0, y: 10, blur: 15, color: .black.opacity(0.1))
    }

    // MARK: Motion

    public enum Motion {
        public enum Duration {
            public static let instant: Double = 0
            public static let fast: Double = 0.1
            public static let normal: Double = 0.2
            public static let slow: Double = 0.3
            public static let slower: Double = 0.5
        }

        public enum Easing {
            public static let linear = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0, y: 0), endControlPoint: UnitPoint(x: 1, y: 1))
            public static let easeIn = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0.4, y: 0), endControlPoint: UnitPoint(x: 1, y: 1))
            public static let easeOut = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0, y: 0), endControlPoint: UnitPoint(x: 0.2, y: 1))
            public static let easeInOut = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0.4, y: 0), endControlPoint: UnitPoint(x: 0.2, y: 1))
        }
    }

    // MARK: Focus

    public enum Focus {
        public static let outlineColor = Color(red: 0, green: 0.369, blue: 0.635)
        public static let outlineWidth: CGFloat = 3
        public static let outlineOffset: CGFloat = 2
        public static let shadowColor = Color(red: 1, green: 1, blue: 1)
        public static let shadowSpread: CGFloat = 3
    }

    // MARK: Density Scales

    public enum Scale {
        public enum Spacious {
            public enum FontSize {
                public static let xs: CGFloat = 11.1
                public static let sm: CGFloat = 13.5
                public static let base: CGFloat = 18
                public static let lg: CGFloat = 24
                public static let xl: CGFloat = 32
                public static let _2xl: CGFloat = 42.6
                public static let _3xl: CGFloat = 56.8
                public static let _4xl: CGFloat = 75.8
                public static let _5xl: CGFloat = 101
            }
            public enum Spacing {
                public static let _1: CGFloat = 5
                public static let _2: CGFloat = 10
                public static let _3: CGFloat = 15
                public static let _4: CGFloat = 20
                public static let _5: CGFloat = 25
                public static let _6: CGFloat = 30
                public static let _8: CGFloat = 40
                public static let _10: CGFloat = 50
                public static let _12: CGFloat = 60
                public static let _16: CGFloat = 80
                public static let _20: CGFloat = 100
                public static let _0_5: CGFloat = 3
                public static let _1_5: CGFloat = 8
                public static let _2_5: CGFloat = 13
            }
            public static let bodyLineHeight: CGFloat = 1.6
            public static let headingLineHeight: CGFloat = 1.3
        }
        public enum Dense {
            public enum FontSize {
                public static let xs: CGFloat = 11.1
                public static let sm: CGFloat = 12.4
                public static let base: CGFloat = 14
                public static let lg: CGFloat = 15.8
                public static let xl: CGFloat = 17.7
                public static let _2xl: CGFloat = 19.9
                public static let _3xl: CGFloat = 22.4
                public static let _4xl: CGFloat = 25.2
                public static let _5xl: CGFloat = 28.4
            }
            public enum Spacing {
                public static let _1: CGFloat = 3
                public static let _2: CGFloat = 6
                public static let _3: CGFloat = 9
                public static let _4: CGFloat = 12
                public static let _5: CGFloat = 15
                public static let _6: CGFloat = 18
                public static let _8: CGFloat = 24
                public static let _10: CGFloat = 30
                public static let _12: CGFloat = 36
                public static let _16: CGFloat = 48
                public static let _20: CGFloat = 60
                public static let _0_5: CGFloat = 2
                public static let _1_5: CGFloat = 5
                public static let _2_5: CGFloat = 8
            }
            public static let bodyLineHeight: CGFloat = 1.4
            public static let headingLineHeight: CGFloat = 1.15
        }
    }
}
